[default]
workshop = [
    "450814997",  # CBA_A3
    "463939057",  # ACE
    "3499977893", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
]
presets = []
dlc = []
optionals = []
parameters = []

[bocr]
extends = "default"
workshop = [
    "2372036642", # Backpack on Chest - Redux
]

[ls]
extends = "default"
workshop = [
    "2162749089", # Legion Studios: Core
]

[jlts]
extends = "default"
workshop = [
    "1940589429", # Just Like The Simulations - The Great War
]

[tas]
extends = "jlts"
workshop = [
    "2058554822", # 3AS (Beta Test)
    "2215872933", # 3AS Terrains (Beta)
]

[optre]
extends = "default"
workshop = [
    "769440155", # Operation TREBUCHET
    "1572627279" # Operation TREBUCHET First Contact
]

[jk]
extends = "default"
workshop = [
    "2894199585", # C-47 Skytrain Mega Pack
]

[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF
    "843593391", # RHS GREF
    "843577117", # RHS USAF
    "843632231", # RHS SAF
]

[tf373]
extends = "rhs"
workshop = [
    "2993751324", # Task Force 373 MH-47G SOAR Chinook
]

[cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons
    "497661914", # CUP Units
    "541888371", # CUP Vehicles
]

[uk3cb]
extends = "default"
workshop = [
    "893349825" # 3CB BAF Vehicles
]

[usaf]
extends = "default"
workshop = [
    "2397360831", # USAF Mod - Main
    "2397376046", # USAF Mod - Utility
    "2226368165", # USAF_AC130_BETA
]

[sab]
extends = "default"
workshop = [
    "375880426", # Lockheed C-130
]

[ws]
extends = "default"
workshop = [
    "2636962953", # Western Sahara - Creator DLC Compatibility Data
]

[vn]
extends = "default"
workshop = [
    "2477276806", # S.O.G. Prairie Fire - Creator DLC Compatibility Data
]

[csla]
extends = "default"
workshop = [
    "2503886780", # CSLA - Iron Curtain - Creator DLC Compatibility Data
]

[gm]
extends = "default"
workshop = [
    "1776428269", # Global Mobilization - Creator DLC Compatibility Data
]

[spe]
extends = "default"
workshop = [
    "2991828484", # Spearhead 1944 - Creator DLC Compatibility Data
]

[rf]
extends = "default"
workshop = [
    "3150497912", # Reaction Forces - Creator DLC Compatibility Data
]